export const ABOUT_DATA = {
  id: "a",
  text: "Привіт! Я Женя, дизайнер інтер'єрів з понад 15 роками досвіду. Обожнюю створювати атмосферні та елегантні простори.",
  // text: "Jane Kuznetsova is an interior designer and creative based out of Kyiv, Ukraine. Her design aesthetic can be described as eclectic, curated and intentional.",
  image: {
    src: "/images/profile-light-blue.png",
    alt: "Portrait of Jane Kuznetsova, an interior designer.",
  },
};

export const CONTACTS_DATA = {
  details: [
    {
      id: "a",
      title: "Пошта",
      value: "jendesign@gmail.com",
      link: "mailto:jendesign@gmail.com",
    },
    {
      id: "b",
      title: "Телефон",
      value: "+38 093 555-44-33",
      link: "tel:+38 093 555-44-33",
    },
    {
      id: "c",
      title: "Інстаграм",
      value: "@eugenia_kuznetsova",
      link: "https://www.instagram.com/eugenia_kuznetsova/",
    },
    {
      id: "d",
      title: "Телеграм",
      value: "@EugeniaKuznetsova",
      link: "https://t.me/EugeniaKuznetsova",
    },
  ],
  fullName: "Євгенія Кузнєцова",
  text: "Будь ласка, зателефонуйте мені, якщо у вас є які-небудь питання або ви бажаєте домовитись про консультацію.",
  country: "Україна",
  city: "Київ",
  image: {
    src: "/images/dragomanova_project_006.jpg",
    alt: "Інтер'єр вітальні",
  },
};

export const PROJECTS = [
  {
    id: 1,
    title: "Басейна",
    images: [
      {
        id: "a",
        imageUrl: "/images/Baseyna/basseynaya_project_011.jpg",
        alt: "",
        gridSpan: 5,
        aspectRatio: 3 / 2,
      },
      {
        id: "b",
        imageUrl: "/images/Baseyna/basseynaya_project_022.jpg",
        alt: "",
        gridSpan: 4,
        aspectRatio: 4 / 5,
        display: "none",
      },
      {
        id: "c",
        imageUrl: "/images/Baseyna/basseynaya_project_058.jpg",
        alt: "",
        gridSpan: 3,
        aspectRatio: 3 / 2,
        display: "none",
      },
    ],
    route: "baseyna",
  },
  {
    id: 2,
    title: "Дельмар",
    images: [
      {
        id: "z",
        imageUrl: "/images/Dragomirova/dragomirova_project_012.jpg",
        alt: "",
        gridSpan: 5,
        aspectRatio: 3 / 2,
      },
      {
        id: "x",
        imageUrl: "/images/Dragomirova/dragomirova_project_013.jpg",
        alt: "",
        gridSpan: 3,
        aspectRatio: 3 / 2,
      },
      {
        id: "c",
        imageUrl: "/images/Dragomirova/dragomirova_project_038.jpg",
        alt: "",
        gridSpan: 4,
        aspectRatio: 3 / 2,
        display: "none",
      },
    ],
    route: "delmar",
  },
  {
    id: 3,
    title: "Коновальця",
    images: [
      {
        id: "z",
        imageUrl: "/images/Konovalca/konovalca_project_030.jpg",
        alt: "",
        gridSpan: 3,
        aspectRatio: 2 / 3,
      },
      {
        id: "x",
        imageUrl: "/images/Konovalca/konovalca_project_001.jpg",
        alt: "",
        gridSpan: 4,
        aspectRatio: 3 / 2,
      },
      {
        id: "c",
        imageUrl: "/images/Konovalca/konovalca_project_051.jpg",
        alt: "",
        gridSpan: 5,
        aspectRatio: 3 / 2,
        display: "none",
      },
    ],
    route: "konovalca",
  },
];

export const PROJECTS_DATA = [
  {
    id: 1,
    // name: `Квартира на Басейній`,
    name: "Басейна",
    route: "baseyna",
    client: "Яна Зужко",
    date: "Червень 2020",
    location: "Київ, Печерський район",
    size: "180m²",
    projectInfo: [
      {
        id: "h",
        category: "Місто",
        text: "Київ, Печерський район",
      },
      {
        id: "j",
        category: "Площа",
        text: "93м2",
      },
      {
        id: "k",
        category: "Рік реалізації",
        text: "2022",
      },
    ],
    plans: [
      {
        id: "b",
        image: "/images/dragomanova_plans_001.jpeg",
        alt: "",
        caption: "Підвал",
      },
      {
        id: "n",
        image: "/images/dragomanova_plans_002.jpeg",
        alt: "",
        caption: "Перший поверх",
      },
      {
        id: "m",
        image: "/images/dragomanova_plans_003.jpeg",
        alt: "",
        caption: "Другий поверх",
      },
    ],
    heroImg: "/images/Baseyna/basseynaya_project_020.jpg",
    infoImg: "/images/Baseyna/basseynaya_project_022.jpg",
    prevNextImg: {
      src: "/images/Baseyna/basseynaya_project_024.jpg",
      alt: "...to be filled",
      aspectRatio: 2 / 3,
    },
    images: [
      {
        id: "t",
        imgPath: "/images/Baseyna/basseynaya_project_001.jpg",
        alt: "",
        aspectRatio: 4 / 3,
        layout: "default",
        span: `col-start / col-end`,
      },
      {
        id: "y",
        imgPath: "/images/Baseyna/basseynaya_project_004.jpg",
        alt: "",
        aspectRatio: 3 / 4,
        span: `col-start / span 5`,
        orientation: "vertical",
      },
      {
        id: "u",
        imgPath: "/images/Baseyna/basseynaya_project_012.jpg",
        alt: "",
        aspectRatio: 3 / 4,
        span: `7 / col-end`,
        orientation: "vertical",
      },
      {
        id: "i",
        imgPath: "/images/Baseyna/basseynaya_project_007.jpg",
        alt: "",
        aspectRatio: 3 / 4,
        span: `4 / 10`,
        orientation: "vertical",
      },
      {
        id: "o",
        imgPath: "/images/Baseyna/basseynaya_project_014.jpg",
        alt: "",
        aspectRatio: 4 / 3,
        layout: "default",
        span: `col-start / col-end`,
      },
      {
        id: "p",
        imgPath: "/images/Baseyna/basseynaya_project_053.jpg",
        alt: "",
        aspectRatio: 3 / 4,
        span: `4 / 10`,
        orientation: "vertical",
      },
      {
        id: "a",
        imgPath: "/images/Baseyna/basseynaya_project_026.jpg",
        alt: "",
        aspectRatio: 3 / 4,
        span: `col-start / span 5`,
        orientation: "vertical",
      },
      {
        id: "s",
        imgPath: "/images/Baseyna/basseynaya_project_025.jpg",
        alt: "",
        aspectRatio: 3 / 4,
        span: `7 / col-end`,
        orientation: "vertical",
      },
      {
        id: "d",
        imgPath: "/images/Baseyna/basseynaya_project_038.jpg",
        alt: "",
        aspectRatio: 16 / 9,
        layout: "full",
        span: `full-start / full-end`,
      },
      {
        id: "f",
        imgPath: "/images/Baseyna/basseynaya_project_046.jpg",
        alt: "",
        aspectRatio: 4 / 3,
        span: `col-start / span 5`,
      },
      {
        id: "g",
        imgPath: "/images/Baseyna/basseynaya_project_044.jpg",
        alt: "",
        aspectRatio: 4 / 3,
        span: `7 / col-end`,
      },
      {
        id: "h",
        imgPath: "/images/Baseyna/basseynaya_project_033.jpg",
        alt: "",
        aspectRatio: 4 / 3,
        span: `col-start / col-end`,
        layout: "default",
      },
      {
        id: "j",
        imgPath: "/images/Baseyna/basseynaya_project_029.jpg",
        alt: "",
        aspectRatio: 3 / 4,
        span: `col-start / span 5`,
        orientation: "vertical",
      },
      {
        id: "k",
        imgPath: "/images/Baseyna/basseynaya_project_035.jpg",
        alt: "",
        aspectRatio: 3 / 4,
        span: `7 / col-end`,
        orientation: "vertical",
      },
      {
        id: "l",
        imgPath: "/images/Baseyna/basseynaya_project_028.jpg",
        alt: "",
        aspectRatio: 4 / 3,
        span: `col-start / col-end`,
        layout: "default",
      },
    ],
  },
  {
    id: 2,
    name: "Дельмар",
    route: "delmar",
    client: "Богдан Сірий",
    date: "Жовтень 2021",
    location: "Київ, Печерський район",
    size: "154m²",
    projectInfo: [
      {
        id: "h",
        category: "Місто",
        text: "Київ, Печерський район",
      },
      {
        id: "j",
        category: "Площа",
        text: "90m²",
      },
      {
        id: "k",
        category: "Рік реалізації",
        text: "2021",
      },
    ],
    heroImg: "/images/Dragomirova/dragomirova_project_014.jpg",
    infoImg: "/images/Dragomirova/dragomirova_project_015.jpg",
    prevNextImg: {
      src: "/images/Dragomirova/dragomirova_project_014.jpg",
      alt: "...to be filled",
      aspectRatio: 3 / 2,
    },
    plans: [
      {
        id: "b",
        image: "/images/dragomanova_plans_001.jpeg",
        alt: "",
        caption: "Підвал",
      },
      {
        id: "n",
        image: "/images/dragomanova_plans_002.jpeg",
        alt: "",
        caption: "Перший поверх",
      },
      {
        id: "m",
        image: "/images/dragomanova_plans_003.jpeg",
        alt: "",
        caption: "Другий поверх",
      },
    ],
    images: [
      {
        id: "t",
        imgPath: "/images/Dragomirova/dragomirova_project_004.jpg",
        alt: "",
        aspectRatio: 4 / 3,
        layout: "default",
        span: `col-start / col-end`,
      },
      {
        id: "y",
        imgPath: "/images/Dragomirova/dragomirova_project_011.jpg",
        alt: "",
        aspectRatio: 4 / 3,
        span: `col-start / span 5`,
      },
      {
        id: "u",
        imgPath: "/images/Dragomirova/dragomirova_project_014.jpg",
        alt: "",
        aspectRatio: 4 / 3,
        span: `7 / col-end`,
      },
      {
        id: "t",
        imgPath: "/images/Dragomirova/dragomirova_project_048.jpg",
        alt: "",
        aspectRatio: 4 / 3,
        layout: "default",
        span: `col-start / col-end`,
      },
      {
        id: "y",
        imgPath: "/images/Dragomirova/dragomirova_project_019.jpg",
        alt: "",
        aspectRatio: 3 / 4,
        span: `col-start / span 5`,
      },
      {
        id: "u",
        imgPath: "/images/Dragomirova/dragomirova_project_049.jpg",
        alt: "",
        aspectRatio: 3 / 4,
        span: `7 / col-end`,
      },
      {
        id: "t",
        imgPath: "/images/Dragomirova/dragomirova_project_038.jpg",
        alt: "",
        aspectRatio: 16 / 9,
        layout: "full",
        span: `full-start / full-end`,
      },
      {
        id: "y",
        imgPath: "/images/Dragomirova/dragomirova_project_044.jpg",
        alt: "",
        aspectRatio: 4 / 3,
        span: `col-start / span 5`,
      },
      {
        id: "u",
        imgPath: "/images/Dragomirova/dragomirova_project_036.jpg",
        alt: "",
        aspectRatio: 4 / 3,
        span: `7 / col-end`,
      },
      {
        id: "t",
        imgPath: "/images/Dragomirova/dragomirova_project_029.jpg",
        alt: "",
        aspectRatio: 4 / 3,
        layout: "default",
        span: `col-start / col-end`,
      },
      {
        id: "t",
        imgPath: "/images/Dragomirova/dragomirova_project_031.jpg",
        alt: "",
        aspectRatio: 4 / 3,
        layout: "default",
        span: `col-start / col-end`,
      },
    ],
  },
  {
    id: 3,
    name: "Коновальця",
    route: "konovalca",
    client: "Богдан Сірий",
    date: "Жовтень 2021",
    location: "Київ, Печерський район",
    size: "154m²",
    projectInfo: [
      {
        id: "h",
        category: "Місце",
        text: "Київ, Печерський район",
      },
      {
        id: "j",
        category: "Розмір",
        text: "154m²",
      },
      {
        id: "k",
        category: "Замовник",
        text: "Богдан Сірий",
      },
    ],
    heroImg: "/images/Konovalca/konovalca_project_003.jpg",
    infoImg: "/images/Konovalca/konovalca_project_001v.jpg",
    prevNextImg: {
      src: "/images/Konovalca/konovalca_project_003.jpg",
      alt: "...to be filled",
      aspectRatio: 3 / 2,
    },
    plans: [
      {
        id: "b",
        image: "/images/dragomanova_plans_001.jpeg",
        alt: "",
        caption: "Підвал",
      },
      {
        id: "n",
        image: "/images/dragomanova_plans_002.jpeg",
        alt: "",
        caption: "Перший поверх",
      },
      {
        id: "m",
        image: "/images/dragomanova_plans_003.jpeg",
        alt: "",
        caption: "Другий поверх",
      },
    ],
    images: [
      {
        id: "t",
        imgPath: "/images/Konovalca/konovalca_project_002.jpg",
        alt: "",
        aspectRatio: 4 / 3,
        layout: "default",
        span: `col-start / col-end`,
      },
      {
        id: "y",
        imgPath: "/images/Konovalca/konovalca_project_004.jpg",
        alt: "",
        aspectRatio: 4 / 3,
        layout: "default",
        span: `col-start / col-end`,
      },
      {
        id: "u",
        imgPath: "/images/Konovalca/konovalca_project_005.jpg",
        alt: "",
        aspectRatio: 4 / 3,
        span: `col-start / span 5`,
      },
      {
        id: "i",
        imgPath: "/images/Konovalca/konovalca_project_006.jpg",
        alt: "",
        aspectRatio: 4 / 3,
        span: `7 / col-end`,
      },
      {
        id: "p",
        imgPath: "/images/Konovalca/konovalca_project_032.jpg",
        alt: "",
        aspectRatio: 3 / 4,
        span: `4 / 10`,
        orientation: "vertical",
      },
      {
        id: "a",
        imgPath: "/images/Konovalca/konovalca_project_026.jpg",
        alt: "",
        aspectRatio: 3 / 4,
        span: `col-start / span 5`,
      },
      {
        id: "s",
        imgPath: "/images/Konovalca/konovalca_project_033.jpg",
        alt: "",
        aspectRatio: 3 / 4,
        span: `7 / col-end`,
      },
      {
        id: "d",
        imgPath: "/images/Konovalca/konovalca_project_029.jpg",
        alt: "",
        aspectRatio: 3 / 4,
        span: `4 / 10`,
        orientation: "vertical",
      },
      {
        id: "i",
        imgPath: "/images/Konovalca/konovalca_project_049.jpg",
        alt: "",
        aspectRatio: 16 / 9,
        layout: "full",
        span: `full-start / full-end`,
      },
      {
        id: "f",
        imgPath: "/images/Konovalca/konovalca_project_050.jpg",
        alt: "",
        aspectRatio: 4 / 3,
        span: `col-start / span 5`,
      },
      {
        id: "g",
        imgPath: "/images/Konovalca/konovalca_project_053.jpg",
        alt: "",
        aspectRatio: 4 / 3,
        span: `7 / col-end`,
      },
      {
        id: "h",
        imgPath: "/images/Konovalca/konovalca_project_021.jpg",
        alt: "",
        aspectRatio: 4 / 3,
        layout: "default",
        span: `col-start / col-end`,
      },
      {
        id: "j",
        imgPath: "/images/Konovalca/konovalca_project_024.jpg",
        alt: "",
        aspectRatio: 4 / 3,
        layout: "default",
        span: `col-start / col-end`,
      },
      {
        id: "k",
        imgPath: "/images/Konovalca/konovalca_project_008.jpg",
        alt: "",
        aspectRatio: 3 / 4,
        span: `col-start / span 5`,
      },
      {
        id: "l",
        imgPath: "/images/Konovalca/konovalca_project_010.jpg",
        alt: "",
        aspectRatio: 3 / 4,
        span: `7 / col-end`,
      },
      {
        id: "z",
        imgPath: "/images/Konovalca/konovalca_project_011.jpg",
        alt: "",
        aspectRatio: 4 / 3,
        layout: "default",
        span: `col-start / col-end`,
      },
      {
        id: "mm",
        imgPath: "/images/Konovalca/konovalca_project_048.jpg",
        alt: "",
        aspectRatio: 3 / 4,
        span: `4 / 10`,
      },
      {
        id: "x",
        imgPath: "/images/Konovalca/konovalca_project_018.jpg",
        alt: "",
        aspectRatio: 4 / 3,
        span: `col-start / span 5`,
      },
      {
        id: "c",
        imgPath: "/images/Konovalca/konovalca_project_020.jpg",
        alt: "",
        aspectRatio: 4 / 3,
        span: `7 / col-end`,
      },
      {
        id: "v",
        imgPath: "/images/Konovalca/konovalca_project_036.jpg",
        alt: "",
        aspectRatio: 3 / 4,
        span: `4 / 10`,
        orientation: "vertical",
      },
      {
        id: "b",
        imgPath: "/images/Konovalca/konovalca_project_040.jpg",
        alt: "",
        aspectRatio: 3 / 4,
        span: `4 / 10`,
        orientation: "vertical",
      },
      {
        id: "n",
        imgPath: "/images/Konovalca/konovalca_project_041.jpg",
        alt: "",
        aspectRatio: 3 / 4,
        span: `col-start / span 5`,
      },
      {
        id: "m",
        imgPath: "/images/Konovalca/konovalca_project_042.jpg",
        alt: "",
        aspectRatio: 3 / 4,
        span: `7 / col-end`,
      },
    ],
  },
];
